import mongoose from "mongoose";
import Feud from "./Feuds.js";
import Company from "./Company.js";

const { Schema } = mongoose;

const UserSchema = new mongoose.Schema(
  {
    firstName: {
      type: String,
      required: true,
      min: 2,
      max: 50,
    },
    lastName: {
      type: String,
      required: true,
      min: 2,
      max: 50,
    },
    email: {
      type: String,
      required: true,
      max: 50,
      unique: true,
    },
    password: {
      type: String,
      required: true,
      min: 5,
    },
    picturePath: {
      type: String,
      default: "",
    },
    alignment: {
      type: String,
      default: "heel",
    },
    popularity: {
      type: Number,
      default: 7,
    },
    wealth: {
      type: Number,
      default: 1000,
    },
    friends: {
      type: Array,
      default: [],
    },
    savegame: {
      type: Object,
      default: {
        companies: [
          {
            id:1,
            name: "WWE",
            preferredCharisma: "comedic",
            inRingBenchmark: 3,
            popularityBenchmark: 2,
            bookerOpinion: 2,
          },
          {
            id:2,
            name: "AEW",
            preferredCharisma: "menacing",
            inRingBenchmark: 2,
            popularityBenchmark: 3,
            bookerOpinion: 7,
          },
          {
            id:3,
            name: "NJPW",
            preferredCharisma: "menacing",
            inRingBenchmark: 5,
            popularityBenchmark: 3,
            bookerOpinion: 7,
          },
          {
            id:4,
            name: "Indie",
            preferredCharisma: "comedic",
            inRingBenchmark: 5,
            popularityBenchmark: 3,
            bookerOpinion: 7,
          },
          // Add more companies here with their properties
          // ...
        ],
        wrestlers: [
          {
            id: 1,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: "Stone Cold Steve Austin",
            alignment: "face",
            popularity: 5,
            inRingSkill: 0,
            pastFeuds: [],
            charisma: "menacing",
            relationship: 0,
            tags: [],
            company: "WWE",
            bookerRelationship: 7,
          },
          {
            id: 2,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: "The Rock",
            alignment: "face",
            popularity: 6,
            pastFeuds: [],
            inRingSkill: 0,
            charisma: "comedic",
            relationship: 0,
            tags: [],
            company: "WWE",
            bookerRelationship: 7,
          },
          {
            id: 3,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            pastFeuds: [],
            name: "Daniel Bryan",
            alignment: "face",
            popularity: 2,
            inRingSkill: 4,
            charisma: "comedic",
            relationship: 0,
            tags: [],
            company: "WWE",
            bookerRelationship: 7,
          },
          {
            id: 4,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: "Becky Lynch",
            alignment: "heel",
            popularity: 6,
            pastFeuds: [],
            inRingSkill: 9,
            charisma: "menacing",
            relationship: 0,
            tags: [],
            company: "WWE",
            bookerRelationship: 7,
          },
          {
            id: 5,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: "Randy Savage",
            pastFeuds: [],
            alignment: "heel",
            popularity: 5,
            inRingSkill: 4,
            charisma: "menacing",
            relationship: 0,
            tags: [],
            company: "WWE",
            bookerRelationship: 7,
          },
          {
            id: 6,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: "Bayley",
            alignment: "face",
            popularity: 2,
            inRingSkill: 0,
            charisma: "menacing",
            relationship: 0,
            tags: [],
            pastFeuds: [],
            company: "WWE",
            bookerRelationship: 7,
          },
          {
            id: 12,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: "Sasha Banks",
            alignment: "heel",
            popularity: 7,
            inRingSkill: 6,
            charisma: "menacing",
            relationship: 0,
            tags: [],
            pastFeuds: [],
            company: "WWE",
            bookerRelationship: 7,
          },
          
          
          {
            id: 19,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'John Cena',
            alignment: 'face',
            popularity: 8,
            inRingSkill: 0,
            pastFeuds: [],
            charisma: 'menacing',
            relationship: 0,
            tags: [],
            company: 'WWE',
            bookerRelationship: 7,
          },
          {
            id: 20,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Randy Orton',
            alignment: 'heel',
            popularity: 9,
            inRingSkill: 0,
            pastFeuds: [],
            charisma: 'comedic',
            relationship: 0,
            tags: [],
            company: 'WWE',
            bookerRelationship: 7,
          },
          {
            id: 21,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Seth Rollins',
            alignment: 'face',
            popularity: 2,
            inRingSkill: 8,
            pastFeuds: [],
            charisma: 'menacing',
            relationship: 0,
            tags: [],
            company: 'WWE',
            bookerRelationship: 7,
          },
          {
            id: 22,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Braun Strowman',
            alignment: 'face',
            pastFeuds: [],
            popularity: 5,
            inRingSkill: 6,
            charisma: 'comedic',
            relationship: 0,
            tags: [],
            company: 'WWE',
            bookerRelationship: 7,
          },
          {
            id: 23,
            name: 'Roman Reigns',
            isChampion: true,
            championshipHeld: {id:1,
              name: "WWE Championship",
              style: "WWE Champion",
              currentHolder: {},
              daysHeld: 0,
              dateWon: "",
              dateLost: "",
              pastHolders: [],
              company: "WWE",
            },
            pronoun: 'he',
            isFeuding: false,
           
            alignment: 'face',
            popularity: 7,
            inRingSkill: 5,
            pastFeuds: [],
            charisma: 'menacing',
            relationship: 0,
            tags: [],
            company: 'WWE',
            bookerRelationship: 7,
          },
          {
            id: 24,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'The Miz',
            alignment: 'heel',
            popularity: 5,
            inRingSkill: 3,
            pastFeuds: [],
            charisma: 'comedic',
            relationship: 0,
            tags: [],
            company: 'WWE',
            bookerRelationship: 7,
          },
          {
            id: 25,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Finn Balor',
            alignment: 'face',
            popularity: 2,
            pastFeuds: [],
            inRingSkill: 0,
            charisma: 'menacing',
            relationship: 0,
            tags: [],
            company: 'WWE',
            bookerRelationship: 7,
          },
          {
            id: 26,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Kevin Owens',
            alignment: 'face',
            popularity: 3,
            inRingSkill: 4,
            charisma: 'comedic',
            bookerRelationship: 7,
            relationship: 0,
            tags: [],
            company: 'WWE',
            pastFeuds: [],
          },
          {
            id: 15,
            isChampion: false,
            championshipHeld: {},
            pastFeuds: [],
            pronoun: 'he',
            isFeuding: false,
            name: "Sami Zayn",
            alignment: "face",
            popularity: 8,
            inRingSkill: 8,
            charisma: "menacing",
            relationship: 0,
            tags: [],
            company: "WWE",
            bookerRelationship: 7,
          },
          
          {
            id: 30,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Cody Rhodes',
            alignment: 'face',
            popularity: 7,
            inRingSkill: 8,
            pastFeuds: [],
            charisma: 'menacing',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          },
          {
            id: 31,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Chris Jericho',
            alignment: 'heel',
            popularity: 9,
            inRingSkill: 9,
            pastFeuds: [],
            charisma: 'comedic',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          },
          {
            id: 32,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Jon Moxley',
            alignment: 'face',
            popularity: 8,
            inRingSkill: 9,
            pastFeuds: [],
            charisma: 'menacing',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          },
          {
            id: 33,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Hikaru Shida',
            alignment: 'face',
            popularity: 7,
            inRingSkill: 8,
            pastFeuds: [],
            charisma: 'comedic',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          },
          {
            id: 34,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Penta El Zero M',
            alignment: 'heel',
            popularity: 8,
            inRingSkill: 9,
            pastFeuds: [],
            charisma: 'menacing',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          },
          {
            id: 35,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Rey Fenix',
            alignment: 'face',
            popularity: 8,
            inRingSkill: 9,
            pastFeuds: [],
            charisma: 'menacing',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          },
          {
            id: 36,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'MJF',
            alignment: 'heel',
            popularity: 8,
            inRingSkill: 8,
            pastFeuds: [],
            charisma: 'comedic',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          },
          {
            id: 37,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Darby Allin',
            alignment: 'face',
            popularity: 7,
            inRingSkill: 8,
            pastFeuds: [],
            charisma: 'menacing',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          },
          {
            id: 38,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Thunder Rosa',
            alignment: 'face',
            popularity: 7,
            inRingSkill: 8,
            pastFeuds: [],
            charisma: 'comedic',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          },
          {
            id: 39,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'PAC',
            alignment: 'heel',
            popularity: 8,
            inRingSkill: 9,
            pastFeuds: [],
            charisma: 'menacing',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          },
          {
            id: 40,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Serena Deeb',
            alignment: 'face',
            popularity: 7,
            inRingSkill: 8,
            pastFeuds: [],
            charisma: 'comedic',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          },
          {
            id: 41,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Eddie Kingston',
            alignment: 'heel',
            popularity: 8,
            inRingSkill: 8,
            pastFeuds: [],
            charisma: 'menacing',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          },
          {
            id: 42,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Orange Cassidy',
            alignment: 'face',
            popularity: 7,
            inRingSkill: 8,
            pastFeuds: [],
            charisma: 'comedic',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          },
          {
            id: 43,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Riho',
            alignment: 'face',
            popularity: 7,
            inRingSkill: 8,
            pastFeuds: [],
            charisma: 'comedic',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          },
          {
            id: 44,
            isChampion: false,
            championshipHeld: {},
            pronoun: 'he',
            isFeuding: false,
            name: 'Miro',
            alignment: 'heel',
            popularity: 8,
            inRingSkill: 9,
            pastFeuds: [],
            charisma: 'menacing',
            relationship: 0,
            tags: [],
            company: 'AEW',
            bookerRelationship: 7,
          }
        ],
        championships: [
          {id:1,
            name: "WWE Championship",
            style: "WWE Champion",
            currentHolder: {
              id: 23,
              isChampion: false,
              championshipHeld: {},
              pronoun: 'he',
              isFeuding: false,
              name: 'Roman Reigns',
              alignment: 'face',
              popularity: 7,
              inRingSkill: 5,
              pastFeuds: [],
              charisma: 'menacing',
              relationship: 0,
              tags: [],
              company: 'WWE',
              bookerRelationship: 7,
            },
            daysHeld: 0,
            dateWon: "",
            dateLost: "",
            pastHolders: [],
            company: "WWE",
          },
          {
            id:2,
            name: "WWE World Heavyweight Championship",
            style: "WWE World Heavyweight Champion",
            currentHolder: {},
            daysHeld: 0,
            dateWon: "",
            dateLost: "",
            pastHolders: [],
            company: "WWE",
          },
          {id:3,
            name: "WWE Tag Team Championship",
            style: "WWE Tag Team Champion",
            currentHolder: {},
            daysHeld: 0,
            dateWon: "",
            dateLost: "",
            pastHolders: [],
            company: "WWE",
          },
          {id:4,
            name: "AEW World Championship",
            style: "AEW World Champion",
            currentHolder: {},
            daysHeld: 0,
            dateWon: "",
            dateLost: "",
            pastHolders: [],
            company: "AEW",
          },
          {
            id:5,
            name: "AEW Championship",
            style: "AEW Champion",
            currentHolder: {},
            daysHeld: 0,
            dateWon: "",
            dateLost: "",
            pastHolders: [],
            company: "AEW",
          },
          
        ],
        feuds: [
    
        ],
        otherFeuds: [
      
        ],
      },
    },
    charisma: {
      type: String,
      default: "menacing",
    },

    isChampion: {
      type: Boolean,
      default: false,
    },
    responseRecieved: {
      type: Boolean,
      default: true,
    },
    pastFeuds: {
      type: Array,
      default: [],
    },
    inRingSkill: {
      type: Number,
      default: 8,
    },
    currentPotentialFeud: {
      type: Object,
      default: {
        name: "Higgins",
        opponent: [
          {
            id: 13,
            isChampion:false,
            championshipHeld:{},
            pronoun:'he',
            isFeuding:true,
            name: "William Harris",
            alignment: "heel",
            popularity: 0,
            inRingSkill: 0,
            charisma: "menacing",
            relationship: 0,
            tags: [],
            company: "WWE",
            bookerRelationship: 7,
          },
        ],
        ally: [],
        requirements: {
          alignment: "face",
          charisma: "menacing",
        },
        length: 2,
        tags: [],
        multiplier: 1.2,
        isCurrentFeud: false,
      },
    },
    activeFeud: {
      type: Object,
      default: {
        name: "Higgins",
        opponent: [
          {
            id: 15,
            name: "Ethan King",
            alignment: "heel",
            popularity: 0,
            inRingSkill: 0,
            charisma: "menacing",
            relationship: 0,
            tags: [],
            company: "WWE",
            bookerRelationship: 7,
          },
        ],
        ally: [],
        requirements: {
          alignment: "face",
          charisma: "menacing",
        },
        length: 2,
        tags: [],
        multiplier: 1.2,
        isCurrentFeud: false,
      },
    },
    currentChampionshipHeld: {
      type: Object,
      default: {},
    },
    titleReigns: {
      type: Array,
      default: [],
    },
    tags: {
      type: Array,
      default: [],
    },
    currentCompany: {
      type: Object,

      default: {
        id:1,
        name: "WWE",
        preferredCharisma: "comedic",
        inRingBenchmark: 3,
        popularityBenchmark: 5,
        bookerOpinion: 7,
      },
    },

    location: String,

    viewedProfile: Number,
    impressions: Number,
  },
  { timestamps: true }
);

const User = mongoose.model("User", UserSchema);
export default User;
